import { User, Project, Board, Task } from './types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Sarah Chen',
    email: 'sarah.chen@taskflow.com',
    avatarUrl: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
    role: 'admin',
  },
  {
    id: 'user-2',
    name: 'Marcus Rodriguez',
    email: 'marcus.r@taskflow.com',
    avatarUrl: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
    role: 'member',
  },
  {
    id: 'user-3',
    name: 'Emma Wilson',
    email: 'emma.wilson@taskflow.com',
    avatarUrl: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=200&h=200&fit=crop',
    role: 'member',
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'project-1',
    name: 'Website Redesign',
    description: 'Complete overhaul of company website with modern design and improved UX',
    color: 'bg-blue-500',
    memberIds: ['user-1', 'user-2', 'user-3'],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-02-10T14:30:00Z',
  },
  {
    id: 'project-2',
    name: 'Mobile App Launch',
    description: 'Development and launch of iOS and Android mobile applications',
    color: 'bg-purple-500',
    memberIds: ['user-1', 'user-2'],
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-02-12T16:45:00Z',
  },
];

export const MOCK_BOARDS: Board[] = [
  {
    id: 'board-1',
    projectId: 'project-1',
    name: 'Main Board',
    columns: [
      {
        id: 'col-1',
        name: 'Backlog',
        color: 'bg-gray-500',
        position: 0,
        taskIds: ['task-1', 'task-2'],
        wipLimit: undefined,
      },
      {
        id: 'col-2',
        name: 'To Do',
        color: 'bg-blue-500',
        position: 1,
        taskIds: ['task-3', 'task-4', 'task-5'],
        wipLimit: 5,
      },
      {
        id: 'col-3',
        name: 'In Progress',
        color: 'bg-yellow-500',
        position: 2,
        taskIds: ['task-6', 'task-7'],
        wipLimit: 3,
      },
      {
        id: 'col-4',
        name: 'Done',
        color: 'bg-green-500',
        position: 3,
        taskIds: ['task-8', 'task-9'],
        wipLimit: undefined,
      },
    ],
  },
  {
    id: 'board-2',
    projectId: 'project-2',
    name: 'Main Board',
    columns: [
      {
        id: 'col-5',
        name: 'Backlog',
        color: 'bg-gray-500',
        position: 0,
        taskIds: ['task-10'],
        wipLimit: undefined,
      },
      {
        id: 'col-6',
        name: 'To Do',
        color: 'bg-blue-500',
        position: 1,
        taskIds: ['task-11'],
        wipLimit: 5,
      },
      {
        id: 'col-7',
        name: 'In Progress',
        color: 'bg-yellow-500',
        position: 2,
        taskIds: ['task-12'],
        wipLimit: 3,
      },
      {
        id: 'col-8',
        name: 'Done',
        color: 'bg-green-500',
        position: 3,
        taskIds: [],
        wipLimit: undefined,
      },
    ],
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Create wireframes for homepage',
    description: 'Design low-fidelity wireframes for the new homepage layout',
    status: 'backlog',
    priority: 'Medium',
    assigneeId: 'user-3',
    dueDate: '2024-03-15T00:00:00Z',
    labels: [
      { id: 'label-1', name: 'Design', color: 'bg-pink-500' },
      { id: 'label-2', name: 'Research', color: 'bg-purple-500' },
    ],
    subtasks: [
      { id: 'sub-1', title: 'Research competitor sites', completed: true },
      { id: 'sub-2', title: 'Sketch initial concepts', completed: false },
    ],
    attachmentCount: 3,
    commentCount: 5,
    boardId: 'board-1',
    columnId: 'col-1',
    position: 0,
    createdAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'task-2',
    title: 'SEO audit and recommendations',
    description: 'Conduct comprehensive SEO audit of current website',
    status: 'backlog',
    priority: 'Low',
    assigneeId: 'user-2',
    dueDate: '2024-03-20T00:00:00Z',
    labels: [{ id: 'label-3', name: 'SEO', color: 'bg-green-500' }],
    subtasks: [],
    attachmentCount: 0,
    commentCount: 2,
    boardId: 'board-1',
    columnId: 'col-1',
    position: 1,
    createdAt: '2024-02-02T11:00:00Z',
  },
  {
    id: 'task-3',
    title: 'Design color palette and typography',
    description: 'Create brand guidelines with colors and fonts',
    status: 'todo',
    priority: 'High',
    assigneeId: 'user-3',
    dueDate: '2024-02-28T00:00:00Z',
    labels: [{ id: 'label-1', name: 'Design', color: 'bg-pink-500' }],
    subtasks: [
      { id: 'sub-3', title: 'Select primary colors', completed: false },
      { id: 'sub-4', title: 'Choose font families', completed: false },
      { id: 'sub-5', title: 'Create style guide', completed: false },
    ],
    attachmentCount: 1,
    commentCount: 8,
    boardId: 'board-1',
    columnId: 'col-2',
    position: 0,
    createdAt: '2024-02-03T09:00:00Z',
  },
  {
    id: 'task-4',
    title: 'Set up development environment',
    description: 'Configure Next.js project with all necessary dependencies',
    status: 'todo',
    priority: 'Urgent',
    assigneeId: 'user-1',
    dueDate: '2024-02-25T00:00:00Z',
    labels: [{ id: 'label-4', name: 'Development', color: 'bg-blue-500' }],
    subtasks: [
      { id: 'sub-6', title: 'Initialize Next.js project', completed: true },
      { id: 'sub-7', title: 'Install Tailwind CSS', completed: true },
      { id: 'sub-8', title: 'Set up ESLint', completed: false },
    ],
    attachmentCount: 0,
    commentCount: 3,
    boardId: 'board-1',
    columnId: 'col-2',
    position: 1,
    createdAt: '2024-02-04T08:30:00Z',
  },
  {
    id: 'task-5',
    title: 'Content strategy workshop',
    description: 'Plan content structure and information architecture',
    status: 'todo',
    priority: 'Medium',
    assigneeId: null,
    dueDate: '2024-03-05T00:00:00Z',
    labels: [
      { id: 'label-5', name: 'Content', color: 'bg-orange-500' },
      { id: 'label-2', name: 'Research', color: 'bg-purple-500' },
    ],
    subtasks: [],
    attachmentCount: 2,
    commentCount: 1,
    boardId: 'board-1',
    columnId: 'col-2',
    position: 2,
    createdAt: '2024-02-05T10:15:00Z',
  },
  {
    id: 'task-6',
    title: 'Build responsive navigation',
    description: 'Implement mobile-first navigation component',
    status: 'in_progress',
    priority: 'High',
    assigneeId: 'user-1',
    dueDate: '2024-02-26T00:00:00Z',
    labels: [{ id: 'label-4', name: 'Development', color: 'bg-blue-500' }],
    subtasks: [
      { id: 'sub-9', title: 'Desktop navigation', completed: true },
      { id: 'sub-10', title: 'Mobile menu', completed: false },
      { id: 'sub-11', title: 'Accessibility audit', completed: false },
    ],
    attachmentCount: 1,
    commentCount: 12,
    boardId: 'board-1',
    columnId: 'col-3',
    position: 0,
    createdAt: '2024-02-06T09:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Create hero section design',
    description: 'Design impactful above-the-fold hero section',
    status: 'in_progress',
    priority: 'High',
    assigneeId: 'user-3',
    dueDate: '2024-02-27T00:00:00Z',
    labels: [{ id: 'label-1', name: 'Design', color: 'bg-pink-500' }],
    subtasks: [
      { id: 'sub-12', title: 'Concept exploration', completed: true },
      { id: 'sub-13', title: 'High-fidelity mockup', completed: false },
    ],
    attachmentCount: 7,
    commentCount: 15,
    boardId: 'board-1',
    columnId: 'col-3',
    position: 1,
    createdAt: '2024-02-07T11:00:00Z',
  },
  {
    id: 'task-8',
    title: 'Project kickoff meeting',
    description: 'Initial meeting with stakeholders to align on vision',
    status: 'done',
    priority: 'Urgent',
    assigneeId: 'user-1',
    dueDate: '2024-02-10T00:00:00Z',
    labels: [{ id: 'label-6', name: 'Meeting', color: 'bg-yellow-500' }],
    subtasks: [
      { id: 'sub-14', title: 'Prepare agenda', completed: true },
      { id: 'sub-15', title: 'Send invites', completed: true },
      { id: 'sub-16', title: 'Document outcomes', completed: true },
    ],
    attachmentCount: 2,
    commentCount: 6,
    boardId: 'board-1',
    columnId: 'col-4',
    position: 0,
    createdAt: '2024-02-01T08:00:00Z',
  },
  {
    id: 'task-9',
    title: 'Competitor analysis',
    description: 'Research and document competitor websites',
    status: 'done',
    priority: 'Medium',
    assigneeId: 'user-2',
    dueDate: '2024-02-15T00:00:00Z',
    labels: [{ id: 'label-2', name: 'Research', color: 'bg-purple-500' }],
    subtasks: [
      { id: 'sub-17', title: 'Identify key competitors', completed: true },
      { id: 'sub-18', title: 'Analyze features', completed: true },
      { id: 'sub-19', title: 'Create report', completed: true },
    ],
    attachmentCount: 4,
    commentCount: 9,
    boardId: 'board-1',
    columnId: 'col-4',
    position: 1,
    createdAt: '2024-02-02T09:30:00Z',
  },
  {
    id: 'task-10',
    title: 'Define app architecture',
    description: 'Plan technical architecture for mobile apps',
    status: 'backlog',
    priority: 'High',
    assigneeId: 'user-1',
    dueDate: '2024-03-10T00:00:00Z',
    labels: [{ id: 'label-4', name: 'Development', color: 'bg-blue-500' }],
    subtasks: [],
    attachmentCount: 0,
    commentCount: 4,
    boardId: 'board-2',
    columnId: 'col-5',
    position: 0,
    createdAt: '2024-02-08T10:00:00Z',
  },
  {
    id: 'task-11',
    title: 'Design onboarding flow',
    description: 'Create user onboarding experience for first-time users',
    status: 'todo',
    priority: 'Medium',
    assigneeId: 'user-3',
    dueDate: '2024-03-12T00:00:00Z',
    labels: [{ id: 'label-1', name: 'Design', color: 'bg-pink-500' }],
    subtasks: [
      { id: 'sub-20', title: 'User flow diagram', completed: false },
      { id: 'sub-21', title: 'Screen mockups', completed: false },
    ],
    attachmentCount: 5,
    commentCount: 7,
    boardId: 'board-2',
    columnId: 'col-6',
    position: 0,
    createdAt: '2024-02-09T09:00:00Z',
  },
  {
    id: 'task-12',
    title: 'Implement authentication',
    description: 'Set up secure user authentication system',
    status: 'in_progress',
    priority: 'Urgent',
    assigneeId: 'user-2',
    dueDate: '2024-03-01T00:00:00Z',
    labels: [
      { id: 'label-4', name: 'Development', color: 'bg-blue-500' },
      { id: 'label-7', name: 'Security', color: 'bg-red-500' },
    ],
    subtasks: [
      { id: 'sub-22', title: 'Set up OAuth', completed: true },
      { id: 'sub-23', title: 'Implement JWT', completed: false },
      { id: 'sub-24', title: 'Add 2FA support', completed: false },
    ],
    attachmentCount: 1,
    commentCount: 11,
    boardId: 'board-2',
    columnId: 'col-7',
    position: 0,
    createdAt: '2024-02-10T08:00:00Z',
  },
];
